order: [22]
info: |
  Передаваемые опции можно записать в файл <b>~/.mplayer/config</b>, тогда они
  будут использоваться постоянно.<br><br>

  При этом есть отличие. Если из консоли мы пишем:<br>
  <b>mplayer -af volume=10.1:0 video.avi</b><br>
  то в конфиге:<br>
  <b>af=volume=10.1:0</b>
