name: rdiff-backup
info: |
Удобный и мощный скрипт для создания инкрементальных резервных копий
частей файловой системы, создавая снимки файлов одного каталога в другом.
Умеет: работать по SSH, FTP, SMB, копирует только разницу файлов, что 
очень здорово при работе по сети.
ft: bash
